name: C++ MacOS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_DEPS=ON -DCMAKE_INSTALL_PREFIX="/Users/runner/runners/2.168.0/work/or-tools/or-tools/install"
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cmake --build build --config Release --target test -v
    - name: Install
      run: cmake --build build --config Release --target install -v
    - name: Archive
      uses: actions/upload-artifact@v1
      with:
        name: ortools-MacOS-7.5
        path: install
